dependencies {
    // ruleid: mc-g4-vulnerable-log4j
    implementation 'org.apache.logging.log4j:log4j-core:2.14.1'
    // ruleid: mc-g4-vulnerable-log4j
    implementation "org.apache.logging.log4j:log4j-api:2.0.2"
    // ok: mc-g4-vulnerable-log4j
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'
    // ok: mc-g4-vulnerable-log4j
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    // ok: mc-g4-vulnerable-log4j
    implementation 'org.apache.logging.log4j:log4j-core:2.25.0'
}
